export const categoryNames = {
    1: 'Sideswept Dhoti',
    2: 'Side Longhi',
    3: 'Modern Mope',
    4: 'Easy Dhoti',
    5: 'Classic Wideleg',
    6: 'Sideswept Dhoti1',
    7: 'Side Longhi1',
    8: 'Modern Mope1',
    9: 'Easy Dhoti1',
    10: 'Classic Wideleg1',
    11: 'Sideswept Dhoti2',
    12: 'Side Longhi2',
    13: 'Modern Mope2',
    14: 'Easy Dhoti2',
    15: 'Classic Wideleg2',
    16: 'Sideswept Dhoti3',
    17: 'Side Longhi3',
    18: 'Modern Mope3',
    19: 'Easy Dhoti3',
    20: 'Classic Wideleg3',
}